<?php if ( ! defined('ABSPATH') ) {
    exit;
}

/**
 * !! IMPORTANT !!
 *
 * Do not edit this file!
 * To create a new template, simply create a folder in your current theme folder called 'sliced'.
 * You can then copy this file into the 'sliced' folder and edit that copy.
 * This will ensure that your template files are not overwritten if/when you update the Sliced Invoices plugin.
 *
 */
ob_start();
?><!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title><?php esc_html_e( sliced_get_business_name() ) ?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="robots" content="noindex,nofollow">
    <?php do_action('sliced_head'); ?>
    <?php do_action('sliced_payment_head'); ?>


    <link rel='stylesheet' id='dashicons-css'  href='https://acc.petraarmoredvehicles.com/wp-includes/css/dashicons.min.css?ver=5.4.1' media='all' />
    <link rel='stylesheet' id='sliced-invoices_open-sans-css'  href='https://fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&#038;subset=latin%2Clatin-ext&#038;ver=3.8.8' media='all' />
    <link rel='stylesheet' id='sliced-invoices_fontawesome-css'  href='https://acc.petraarmoredvehicles.com/wp-content/plugins/sliced-invoices/public/css/font-awesome.min.css?ver=3.8.8' media='all' />
    <link rel='stylesheet' id='sliced-invoices_bootstrap-css'  href='https://acc.petraarmoredvehicles.com/wp-content/plugins/sliced-invoices/public/css/bootstrap.min.css?ver=3.8.8' media='all' />
    <link rel='stylesheet' id='sliced-invoices_style-css'  href='https://acc.petraarmoredvehicles.com/wp-content/plugins/sliced-invoices/public/css/style.css?ver=3.8.8' media='all' />

            
</head>

<body class="body payment">

    <div class="container sliced-wrap">

        <div class="row sliced-header">
            <div class="col-xs-12 col-sm-6 col-sm-offset-3 sliced-business">
                <a target="_blank" href="https://acc.petraarmoredvehicles.com">
                    <h1>My Blog</h1>                </a>
            </div>
        </div><!-- END row -->

        <div class="row sliced-upper">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2">
                <?php do_action( 'sliced_do_payment' ); ?>
                            </div>
        </div><!-- END row -->

        <div class="row sliced-footer">
            <div class="col-sm-12">
                <div class="footer-text"></div>
            </div>
        </div><!-- END row -->

    </div>

<?php do_action( 'sliced_payment_footer' ); ?>
</body>

</html>
