CREATE TABLE `royalmail_address` (
	`Id` INT(10) NOT NULL AUTO_INCREMENT,
	`Address` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CreatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`Id`) USING BTREE,
	UNIQUE INDEX `Address` (`Address`) USING BTREE
);